#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# (c) ACE 

import os

class Config(object):
    # get a token from @BotFather
    pass
    """
    BOT_TOKEN = os.environ.get("BOT_TOKEN", "6838940253:AAFf5O8pFqnG1Bi09ZEsZ4v9pLqj4ANNBbI")
    API_ID = int(os.environ["API_ID", 17979564]
    API_HASH = os.environ["API_HASH", "b66559ec354de7c42b09c8c38804e902"]
    AUTH_USERS = "5056671625"""
# jisko bhi is repo ko deploy karne me error aa raha ho ( https://t.me/Stubborn1223 ) ye mere TG ka id ha message karke iska screen shot send kar dena me error solve kar dunga. 
